### ISSUE TITLE
High rank village quests missing?

### ISSUE THREAD

**Issue by cflannagan** [JoeLago/MHGDB-iOS#1]
The current version does not have Village 7-star quests and higher, correct? Just wanted to make sure I'm not missing hitting a button somewhere. 

Fantastic app by the way and thanks for the app!

**Comment by JoeLago** [comment]
There aren't any 7* for Generations. Should be releasing Generations Ultimate app soon if you are looking for the Switch game data: https://github.com/JoeLago/MHGUDB-iOS

Thanks for the support!
